# Generated by Django 3.2.7 on 2021-09-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
