# Generated by Django 3.2.7 on 2021-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tag_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='tagged', to='tasks.Tag'),
        ),
    ]
